In [ ]:
import numpy as np 


np_tensor = np.array([[1, 1], [2, 1]])
print(np_tensor.shape)
print(np_tensor)

(2, 2)
[[1 1]
 [2 1]]


In [ ]:
import torch 

torch_tensor = torch.tensor([[1, 1], [2, 1]])
print(torch_tensor)

tensor([[1, 1],
        [2, 1]])


In [ ]:
print(torch_tensor.numpy())

[[1 1]
 [2 1]]


In [ ]:
tensor3D = torch.randn(3, 3, 3, 5, 6)
print(tensor3D.shape)

torch.Size([3, 3, 3, 5, 6])


In [ ]:
print(tensor3D)

tensor([[[[[-2.9571e-01,  1.4948e+00, -1.9581e-01,  1.5211e-01,  5.2131e-01,
             4.6413e-01],
           [-1.7054e-01, -3.2714e-02, -3.5738e-02,  7.9397e-01, -3.8498e-01,
             1.6920e+00],
           [-2.2226e-01,  9.6333e-01, -4.4635e-01,  2.1379e-01, -1.0923e+00,
            -7.0254e-01],
           [ 3.3172e-01,  6.2725e-01, -1.2099e-01,  4.4667e-01,  4.1281e-01,
            -2.6484e-01],
           [ 5.2828e-01, -3.2498e-01,  1.4547e+00,  6.1314e-01, -2.1150e-01,
             1.0508e+00]],

          [[-2.0961e+00, -3.4166e-01,  4.7052e-01,  3.5202e-01,  6.1454e-02,
             9.0934e-01],
           [ 5.7439e-01, -1.5438e+00, -9.6031e-01,  1.9164e+00,  1.2035e+00,
            -1.0654e-01],
           [ 5.4503e-01,  1.3495e+00,  1.0600e+00, -7.2314e-01,  2.9031e-01,
            -5.1785e-01],
           [ 5.1865e-01, -6.4253e-01,  9.9218e-01, -1.0699e+00,  1.8099e-01,
             6.7513e-01],
           [-5.7681e-01, -8.2667e-01, -7.9373e-01,  4.4127e-01, -6.7527

In [ ]:
2 * tensor3D

tensor([[[[[-5.9142e-01,  2.9897e+00, -3.9161e-01,  3.0421e-01,  1.0426e+00,
             9.2826e-01],
           [-3.4107e-01, -6.5427e-02, -7.1475e-02,  1.5879e+00, -7.6997e-01,
             3.3841e+00],
           [-4.4452e-01,  1.9267e+00, -8.9269e-01,  4.2758e-01, -2.1847e+00,
            -1.4051e+00],
           [ 6.6345e-01,  1.2545e+00, -2.4198e-01,  8.9333e-01,  8.2562e-01,
            -5.2969e-01],
           [ 1.0566e+00, -6.4995e-01,  2.9093e+00,  1.2263e+00, -4.2299e-01,
             2.1015e+00]],

          [[-4.1922e+00, -6.8332e-01,  9.4105e-01,  7.0404e-01,  1.2291e-01,
             1.8187e+00],
           [ 1.1488e+00, -3.0876e+00, -1.9206e+00,  3.8327e+00,  2.4069e+00,
            -2.1307e-01],
           [ 1.0901e+00,  2.6990e+00,  2.1200e+00, -1.4463e+00,  5.8063e-01,
            -1.0357e+00],
           [ 1.0373e+00, -1.2851e+00,  1.9844e+00, -2.1399e+00,  3.6198e-01,
             1.3503e+00],
           [-1.1536e+00, -1.6533e+00, -1.5875e+00,  8.8254e-01, -1.3505

In [ ]:
x = torch.tensor([1.1], requires_grad=True)
y = torch.tensor([0.5], requires_grad=True)

In [ ]:
intermediate_tensor = x * y + x

In [ ]:
print(intermediate_tensor.requires_grad)

True


In [ ]:
loss = intermediate_tensor + torch.exp(y) * 2



$ \frac{\partial{loss}}{\partial{x}} $


$ \frac{\partial{loss}}{\partial{y}} $

In [ ]:
loss.backward() # it computes the partial derivatirve of looss regarding to x and y 

In [ ]:
print(x.grad.data) # en vrai grad = derivée partielle de loss  / x

tensor([1.5000])


In [ ]:
print(y.grad.data)

tensor([4.3974])


In [ ]:
import torch




In [ ]:
t = torch.randn(3, 3)
t

tensor([[-0.1529,  0.5660, -0.3319],
        [ 1.5117,  0.8094, -0.7231],
        [ 1.1052,  0.9578,  0.9804]])

In [ ]:
above_0 = t > 0
above_0

tensor([[False,  True, False],
        [ True,  True, False],
        [ True,  True,  True]])

In [ ]:
t[above_0]

tensor([0.5660, 1.5117, 0.8094, 1.1052, 0.9578, 0.9804])

In [ ]:
## no for loops to compute relu ! usually can do most things without loops 



In [ ]:
t = torch.randn(3, 3)
t


tensor([[ 0.0986, -0.0299, -0.9538],
        [ 0.4224,  1.1335,  0.3232],
        [-0.7567, -0.2265,  0.3510]])

In [ ]:
torch.max(t)

tensor(1.1335)

In [ ]:
t = torch.tensor([1.1, 0.1, -2])

relu_t = torch.tensor([1.1, 0.1, 0])


def relu(t):

    result = t.clone()
    result[result<0] = 0

    return result


relu(t), t

(tensor([1.1000, 0.1000, 0.0000]), tensor([ 1.1000,  0.1000, -2.0000]))

In [ ]:
def relu2(t):

    zeros = torch.zeros_like(t)
    return torch.max(t, zeros)

relu2(t)

tensor([1.1000, 0.1000, 0.0000])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6b859965-b858-4b8d-a841-009599aef86e' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>