In [8]:
import numpy as np
def partition_array_arround_zero(array, n ) :
    j = 0 # lastpositiveindex
    for i in range(0, n) :
        if (array[i] < 0) :
            temp = array[i]
            array[i] = array[j]
            array[j]= temp
            j= j+1
    return array

A=[-2,1,2,-3,-4,-1,-2,-3,-6,-4,2,3,2,4,5]
B= np.random.randint(-10,10,100)
n = len(A)
nn=len(B)
partition_array(A,n)
partition_array(B,nn)



array([ -4,  -2,  -3,  -8,  -5,  -6,  -1,  -8,  -1,  -6,  -8, -10,  -2,
        -8,  -7,  -5,  -1,  -1,  -8,  -2,  -2,  -3,  -7,  -6,  -1,  -2,
        -7,  -4,  -8,  -8,  -1,  -9,  -3,  -6,  -2,  -7, -10,  -6,  -5,
        -9,  -1,  -3,  -9,  -5,  -1,  -7,  -1,  -8,  -9,  -7,  -2,  -3,
         3,   5,   1,   6,   1,   5,   7,   6,   0,   5,   8,   9,   6,
         9,   1,   4,   3,   9,   0,   7,   4,   9,   7,   4,   4,   5,
         5,   4,   5,   6,   7,   4,   0,   7,   6,   7,   5,   9,   0,
         9,   1,   1,   2,   4,   5,   7,   0,   5])

In [386]:
def partition_arround(a, start, end):
    pivot =a[start]
    i = start
    for j in range(start, end):
        if(a[j]<=pivot):
            temp=a[j]
            a[j]=a[i]
            a[i]=temp
            i=i+1               
    a[start]=a[i-1]
    a[i-1]=pivot
    return i-1

def quickSort(array, low, high):
    
        if (low <high):
           
            key = partition_arround(array, low, high)
             
            quickSort(array,0, key-1)
            
            quickSort(array,key+1,high)
            
        return array
       

In [387]:
a=np.array([2,6,4,3,1,4,-1,-2])
n= len(a)
index= partition_arround(a,0,n)
print(a)
print ('Pivot index :',index)


[-2  1 -1  2  6  4  4  3]
Pivot index : 3


In [388]:
a=np.array([2,6,4,3,1,4,-1,-2])
n= len(a)
quickSort(a,0,n)

    

array([-2, -1,  1,  2,  3,  4,  4,  6])

In [389]:
b= np.random.randint(-5,5,10)
n= len(b)
quickSort(b,0,n)

array([-4, -1,  0,  0,  0,  1,  3,  4,  4,  4])