In [30]:


x, y = make_regression(n_samples=10**4, n_features=1, n_informative=1, 
                        random_state=0, noise=35) 
print('x.shape = %s y.shape = %s' %(x.shape, y.shape),'\n')
# Loading the data

X=x.reshape((-1,))
print(X)
Y=y

# Creating an array of ones for algebraic calculation
ones = [1] * len(X)

# Main Logic

# Here array of ones will be concatenated with X and transpose will be perform

# This signifies that matrix multiplication can help to obtain new value

# of theta 0 and theta 1
X = np.transpose(np.concatenate((np.array([ones]).reshape(-1, 1),
np.array([X]).reshape(-1, 1)), axis=1))
print(X)

# [[1.  1.  1.  1.  1.  1.  1.  1.  1.  1. ]
# [0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6]]

# Same declaring starting value of two thetas, theta 0 and theta 1,

# Setting value to 0, this means GD will start finding optimal value from 0

zeroes = [0] * X.shape[0]
theta = np.array([zeroes])
#theta = np.array([[np.mean(y),np.mean(y)+np.std(y)/3]])
print('Theta',theta.shape)
# [[0 0]]
# Defining the learning rate

learning_rate = 0.01

htheta = np.dot(theta, X)

print(theta.shape, X.shape, htheta.shape)

# (1, 2) (2, 10) (1, 10)
diff_theta = htheta - Y

partial_derivative_theta = np.dot(diff_theta, np.transpose(X)) / len(Y)

# Implementing the formula define above

theta = theta - learning_rate * partial_derivative_theta

print(theta)

# New Value of theta 0 and theta 1
# [[0.0111  0.02055]]

x.shape = (10000, 1) y.shape = (10000,) 

[ 0.58262411 -1.31093021 -0.76251627 ... -0.22425893  0.17581895
 -0.93942432]
[[ 1.          1.          1.         ...  1.          1.
   1.        ]
 [ 0.58262411 -1.31093021 -0.76251627 ... -0.22425893  0.17581895
  -0.93942432]]
Theta (1, 2)
(1, 2) (2, 10000) (1, 10000)
[[-0.00474389  0.09036748]]


## Now to optimized this value, a for loop can be defined with which it will run until the previous theta and new calculated theta becomes zero

In [28]:
%%time
learning_rate = 0.01
# Threshold for iterating the loop
max_iter = 4000
# Appending all new values of theta (4000 theta values)
new_theta = []
for i in range(max_iter):
    htheta = np.dot(theta, X)
    diff_theta = htheta - Y
    partial_derivative_theta = np.dot(diff_theta, np.transpose(X)) / len(Y)
    theta = theta - learning_rate * partial_derivative_theta
    new_theta.append(theta)
print(new_theta[max_iter-1])
# Therefore the optimal value would be
# [[0.2455339  0.50855582]]

[[-0.30374865  9.25694661]]
CPU times: user 3.09 s, sys: 1.1 s, total: 4.19 s
Wall time: 955 ms


In [10]:
# Loading the same data again
X = [0.8, 1, 1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4, 2.6]
Y = [0.7, 0.65, 0.9, 0.95, 1.1, 1.15, 1.2, 1.4, 1.55, 1.5]
Y = np.array([Y])
X = np.array([X])
# Feteching the optimized theta 0 and theta 1 value
theta0 = new_theta[max_iter-1][0][0]
theta1 = new_theta[max_iter-1][0][1]
# Imputing X into an equation to predict Y
pred_y = theta0 + (theta1 * X.reshape(-1,1)).sum(axis=1)
print(pred_y)
# [0.652379   0.75409007 0.85580115 0.95751223 1.05922331 1.16093438
# 1.26264546 1.36435654 1.46606762 1.5677787 ]
# Computing the mean for calculating r-squared
mean_y =  Y.mean()
# Computing Explained Sum of Squares
ess = ((Y - mean_y) ** 2).sum(axis=1)
# Computing Residual Sum of Squares
rss = ((Y - pred_y) ** 2).sum(axis=1)
# Computing R-Squared
rsquared = 1 - (rss/ess)
print("R-Squared of the Model is: ", rsquared)
# R-Squared of the Model is:  [0.96206043]

[ 7.10180864  8.95319796 10.80458729 12.65597661 14.50736593 16.35875525
 18.21014458 20.0615339  21.91292322 23.76431254]
R-Squared of the Model is:  [-2590.75118854]
